Not Found: /HarryPotter_img.jpg
"GET /HarryPotter_img.jpg HTTP/1.1" 404 2697
Not Found: /HarryPotter_img.jpg
"GET /HarryPotter_img.jpg HTTP/1.1" 404 2697
Not Found: /HarryPotter_img.jpg
"GET /HarryPotter_img.jpg HTTP/1.1" 404 2697
"GET /static/HarryPotter_img.jpg HTTP/1.1" 404 1816
Not Found: /user_project/static/HarryPotter_img.jpg
"GET /user_project/static/HarryPotter_img.jpg HTTP/1.1" 404 2757
Not Found: /user_project/static/HarryPotter_img.jpg
"GET /user_project/static/HarryPotter_img.jpg HTTP/1.1" 404 2884
Not Found: //HarryPotter_img.jpg
"GET //HarryPotter_img.jpg HTTP/1.1" 404 2827
Not Found: /HarryPotter_img.jpg
"GET /HarryPotter_img.jpg HTTP/1.1" 404 2824
Not Found: /HarryPotter_img.jpg
"GET /HarryPotter_img.jpg HTTP/1.1" 404 2824
Not Found: /HarryPotter_img.jpg
"GET /HarryPotter_img.jpg HTTP/1.1" 404 2824
Not Found: /HarryPotter_img.jpg
"GET /HarryPotter_img.jpg HTTP/1.1" 404 2824
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 655, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 554, in get_raw_data_form
    serializer = view.get_serializer()
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AddToCart' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
"GET /cart/addtocart/ HTTP/1.1" 500 94201
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 8493
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 680, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 413, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "D:\Program Files\python\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "D:\Program Files\python\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "D:\Program Files\python\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "D:\Program Files\python\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "D:\Program Files\python\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "D:\Program Files\python\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MultiValueDictKeyError is not JSON serializable
"POST /cart/addtocart/ HTTP/1.1" 500 138773
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 680, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 413, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "D:\Program Files\python\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "D:\Program Files\python\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "D:\Program Files\python\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "D:\Program Files\python\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "D:\Program Files\python\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "D:\Program Files\python\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MultiValueDictKeyError is not JSON serializable
"POST /cart/addtocart/ HTTP/1.1" 500 138773
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 680, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 413, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "D:\Program Files\python\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "D:\Program Files\python\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "D:\Program Files\python\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "D:\Program Files\python\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "D:\Program Files\python\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "D:\Program Files\python\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MultiValueDictKeyError is not JSON serializable
"POST /cart/addtocart/ HTTP/1.1" 500 138773
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 680, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 413, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "D:\Program Files\python\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "D:\Program Files\python\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "D:\Program Files\python\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "D:\Program Files\python\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "D:\Program Files\python\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "D:\Program Files\python\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MultiValueDictKeyError is not JSON serializable
"POST /cart/addtocart/ HTTP/1.1" 500 138773
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 8493
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 8459
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 8459
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 8459
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 8459
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 8459
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 8459
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 8459
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 8459
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 8459
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 8459
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 8459
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 8459
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 8459
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 8459
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 8459
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 680, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 413, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "D:\Program Files\python\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "D:\Program Files\python\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "D:\Program Files\python\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "D:\Program Files\python\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
"POST /cart/addtocart/ HTTP/1.1" 500 121323
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 680, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 413, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "D:\Program Files\python\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "D:\Program Files\python\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "D:\Program Files\python\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "D:\Program Files\python\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
"POST /cart/addtocart/ HTTP/1.1" 500 121323
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 8459
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 680, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 413, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "D:\Program Files\python\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "D:\Program Files\python\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "D:\Program Files\python\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "D:\Program Files\python\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
"POST /cart/addtocart/ HTTP/1.1" 500 121323
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 8459
Unauthorized: /api/login/
"POST /api/login/ HTTP/1.1" 401 63
Not Found: /login/
"POST /login/ HTTP/1.1" 404 2891
Unauthorized: /api/login/
"POST /api/login/ HTTP/1.1" 401 63
Unauthorized: /api/login/
"POST /api/login/ HTTP/1.1" 401 63
Unauthorized: /api/login/
"POST /api/login/ HTTP/1.1" 401 63
Internal Server Error: /user/register/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "D:\Program Files\python\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "D:\Program Files\python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Program Files\python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "D:\Program Files\python\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type AttributeError is not JSON serializable
"POST /user/register/ HTTP/1.1" 500 98991
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 8536
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 40
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 40
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 40
Forbidden: /user/login/
"POST /user/login/ HTTP/1.1" 403 45
Method Not Allowed: /user/login/
"GET /user/login/ HTTP/1.1" 405 40
Forbidden: /user/login/
"POST /user/login/ HTTP/1.1" 403 45
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 8536
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 8536
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 8536
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    if test_func(request.user):
AttributeError: 'AddToCart' object has no attribute 'user'
"POST /cart/addtocart/ HTTP/1.1" 500 93824
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 8536
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    if test_func(request.user):
AttributeError: 'AddToCart' object has no attribute 'user'
"POST /cart/addtocart/ HTTP/1.1" 500 93824
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2905
Not Found: /cart/
"GET /cart/ HTTP/1.1" 404 2964
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 9116
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 655, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 563, in get_raw_data_form
    data = serializer.data.copy()
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\serializers.py", line 257, in data
    self._data = self.get_initial()
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\serializers.py", line 405, in get_initial
    for field in self.fields.values()
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\utils\functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\serializers.py", line 1027, in get_fields
    assert hasattr(self, 'Meta'), (
AssertionError: Class AddToCartSerializer missing "Meta" attribute
"POST /cart/addtocart/ HTTP/1.1" 500 111691
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 655, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 563, in get_raw_data_form
    data = serializer.data.copy()
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\serializers.py", line 257, in data
    self._data = self.get_initial()
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\serializers.py", line 405, in get_initial
    for field in self.fields.values()
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\utils\functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\serializers.py", line 1027, in get_fields
    assert hasattr(self, 'Meta'), (
AssertionError: Class AddToCartSerializer missing "Meta" attribute
"GET /cart/addtocart/ HTTP/1.1" 500 110244
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 655, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 563, in get_raw_data_form
    data = serializer.data.copy()
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\serializers.py", line 257, in data
    self._data = self.get_initial()
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\serializers.py", line 405, in get_initial
    for field in self.fields.values()
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\utils\functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\serializers.py", line 1027, in get_fields
    assert hasattr(self, 'Meta'), (
AssertionError: Class AddToCartSerializer missing "Meta" attribute
"GET /cart/addtocart/ HTTP/1.1" 500 110381
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 7724
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    if test_func(request.user):
AttributeError: 'AddToCart' object has no attribute 'user'
"POST /cart/addtocart/ HTTP/1.1" 500 93528
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 7724
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    if test_func(request.user):
AttributeError: 'AddToCart' object has no attribute 'user'
"POST /cart/addtocart/ HTTP/1.1" 500 93528
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 7724
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    if test_func(request.user):
AttributeError: 'AddToCart' object has no attribute 'user'
"POST /cart/addtocart/ HTTP/1.1" 500 93528
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 7724
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    if test_func(request.user):
AttributeError: 'AddToCart' object has no attribute 'user'
"POST /cart/addtocart/ HTTP/1.1" 500 93528
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 7724
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 7724
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 7724
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 7724
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 7724
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 7724
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Django-Project\user_project\cart\utility.py", line 49, in decorated
    if 'access-token' in request.headers:
AttributeError: module 'django.http.request' has no attribute 'headers'
"POST /cart/addtocart/ HTTP/1.1" 500 92743
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Django-Project\user_project\cart\utility.py", line 49, in decorated
    if 'access-token' in request.headers:
AttributeError: module 'django.http.request' has no attribute 'headers'
"POST /cart/addtocart/ HTTP/1.1" 500 90082
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Django-Project\user_project\cart\utility.py", line 49, in decorated
    if 'access-token' in request.headers:
AttributeError: module 'django.http.request' has no attribute 'headers'
"POST /cart/addtocart/ HTTP/1.1" 500 90082
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Django-Project\user_project\cart\utility.py", line 49, in decorated
    if 'access-token' in request.headers:
AttributeError: module 'django.http.request' has no attribute 'headers'
"POST /cart/addtocart/ HTTP/1.1" 500 90082
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 7724
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Django-Project\user_project\cart\utility.py", line 49, in decorated
    if 'access-token' in request.headers:
AttributeError: module 'django.http.request' has no attribute 'headers'
"POST /cart/addtocart/ HTTP/1.1" 500 90082
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Django-Project\user_project\cart\utility.py", line 49, in decorated
    if 'access-token' in request.headers:
AttributeError: module 'django.http.request' has no attribute 'headers'
"POST /cart/addtocart/ HTTP/1.1" 500 90082
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "D:\Program Files\python\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "D:\Program Files\python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Program Files\python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "D:\Program Files\python\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type function is not JSON serializable
"POST /cart/addtocart/ HTTP/1.1" 500 98271
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "D:\Program Files\python\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "D:\Program Files\python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Program Files\python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "D:\Program Files\python\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type function is not JSON serializable
"POST /cart/addtocart/ HTTP/1.1" 500 98271
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "D:\Program Files\python\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "D:\Program Files\python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Program Files\python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "D:\Program Files\python\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type function is not JSON serializable
"POST /cart/addtocart/ HTTP/1.1" 500 98271
Internal Server Error: /admin/cart/cart/4/change/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\contrib\admin\options.py", line 683, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1888, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1745, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1854, in _changeform_view
    "subtitle": str(obj) if obj else None,
TypeError: __str__ returned non-string (type User)
"GET /admin/cart/cart/4/change/ HTTP/1.1" 500 106646
Internal Server Error: /admin/cart/cart/4/change/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\contrib\admin\options.py", line 683, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1888, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1745, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1854, in _changeform_view
    "subtitle": str(obj) if obj else None,
TypeError: __str__ returned non-string (type User)
"GET /admin/cart/cart/4/change/ HTTP/1.1" 500 106646
Method Not Allowed: /cart/addtocart/
"GET /cart/addtocart/ HTTP/1.1" 405 7724
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Django-Project\user_project\cart\utility.py", line 56, in decorated
    return f(request, user_id, *args, **kwargs)
TypeError: post() takes 2 positional arguments but 3 were given
"POST /cart/addtocart/ HTTP/1.1" 500 95370
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Django-Project\user_project\cart\utility.py", line 56, in decorated
    return f(request, user_id, *args, **kwargs)
TypeError: post() takes 2 positional arguments but 3 were given
"POST /cart/addtocart/ HTTP/1.1" 500 95370
Internal Server Error: /cart/addtocart/
Traceback (most recent call last):
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Crud-operation-Django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Crud-operation-Django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Django-Project\user_project\cart\utility.py", line 44, in decorated
    token = request.query_params.get['access-token']
TypeError: 'method' object is not subscriptable
"POST /cart/addtocart/ HTTP/1.1" 500 95367
